README.md 업데이트: 중요 API에 대한 설명 첨부
ridi/Reader.js pull request #19
Opened 2018-08-08 09:02 UTC by kyungmi

들은대로 적은거라 정확도가 의심되네요 ㅎㅎ
내용 검토 부탁드립니다.

2018-08-08 09:17 UTC, YSYoon commented on README.md
> +- `serialized range`: (스파인 내) 범위를 나타내는 자체 포맷 (예: `0/171:0,0/171:30`)
serialized range 는 자체 포맷은 아니고.. rangy에서 사용되는 포맷입니다

2018-08-08 09:27 UTC, DavinAhn requested changes

2018-08-08 09:27 UTC, DavinAhn commented on README.md
> +- `serialized range`: (스파인 내) 범위를 나타내는 자체 포맷 (예: `0/171:0,0/171:30`)
(우리가 만든게 아니라는 의미에서) 자체 포맷은 아니고 [rangy.js](https://github.com/timdown/rangy)의 [Serializer-Module](https://github.com/timdown/rangy/wiki/Serializer-Module)에서 정한 포맷이에요.

2018-08-08 09:27 UTC, DavinAhn commented on README.md
> +	- 팝업 주석 링크일 경우 `type: 'epub:type'` 반환
`epub:type`은 속성 명이고 반환하는 값은 `epub:type` 속성의 값이에요.
(예: `type: 'noteref'`)

2018-08-08 09:27 UTC, DavinAhn commented on README.md
> +    - 사용 후 페이지 재계산 필요
`재계산` 보다는 `계산`이 정확한것 같아요.
`재계산`이라 하니 이미지 보정 전후로 페이지 계산을 해야 한다는 의미로 오해할 수 있을것 같아요.

2018-08-08 09:27 UTC, DavinAhn commented on README.md
> +	- 특정 (마우스) 포인트에 `<img>` 태그가 존재하는 경우 `src` 애트리뷰트 값 반환
`마우스 또는 터치`나 셀렉션에서 이벤트 명을 언급해 설명하면 좋을것 같아요.

2018-08-08 09:30 UTC, namenu commented
👍 
변경과 관련은 없지만 `Compatbility` 오타가 있네요.

2018-08-09 00:11 UTC, kyungmi commented on README.md
> +- `serialized range`: (스파인 내) 범위를 나타내는 자체 포맷 (예: `0/171:0,0/171:30`)
아 완전히 같은거였군요!

2018-08-09 00:30 UTC, DavinAhn approved these changes

2018-08-09 00:39 UTC, DavinAhn commented on README.md
> +- `serialized range`: (스파인 내) 범위를 나타내는 자체 포맷 (예: `0/171:0,0/171:30`)
넵, 라이브러리 마개조는 다른 부분(*1)에서만 이뤄졌고 포맷은 그대로 사용하고 있어요.

*1
- rangy.js에서 용량을 줄이기 위해 Serializer-Module만 추출해서 사용하고 있어요.
- Serializer-Module에서도 속도를 위해 crc 체크를 제거했어요.

2018-08-10 03:39 UTC, merged