TTS 문장 이동 기능을 구현한 branch입니다.
ridi/Reader.js pull request #2
Opened 2016-11-01 10:17 UTC by kgwangrae

2016-11-04 10:26 UTC, DavinAhn requested changes

2016-11-04 10:26 UTC, DavinAhn commented on src/common/tts/TTSChunk.es6
> +    // |-----------------------------------------|-End Word-|--------------------|
'EndWord-|'의 '|'와 '|paddingRight(EP)'의 '|'가 같은 열에 있어야 하지 않나요?

2016-11-04 10:26 UTC, DavinAhn commented on src/common/tts/TTSPiece.es6
> +  // node.nodeValue (text 아님) 의 좌측 끝에서 startWordIndex에 해당하는 단어의
node.nodeValue는 text일 수 있는데..
여기서 말한 text는 TTSPiece의 프로퍼티인 text인거겠죠?

2016-11-07 06:13 UTC, kgwangrae commented on src/common/tts/TTSChunk.es6
> +    // |-----------------------------------------|-End Word-|--------------------|
음.. 기억을 더듬어보니 endOffset까지의 text가 EP의 text를 다 포함하지 않을 수도 있는데, 그러한 경우를 상정해서 저렇게 주석을 남겼던 것 같네요

2016-11-07 06:24 UTC, kgwangrae commented on src/common/tts/TTSPiece.es6
> +  // node.nodeValue (text 아님) 의 좌측 끝에서 startWordIndex에 해당하는 단어의
그렇습니다. 애매하게 받아들여질 수 있는 부분인 것 같아 text -> piece.text로 해당 부분을 수정하였습니다.

2016-11-07 12:37 UTC, merged